# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftLearn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftLearn

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SnapKit'
  

  target 'swiftLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftLearnUITests' do
    # Pods for testing
  end

end
